###
GET  http://localhost:4000

###
DELETE http://localhost:4000/delete/9

###
POST http://localhost:4000/api/info?id=8
Content-Type: application/json

{
  "information" : "very cool"
}

###
PUT http://localhost:4000/api/?word=marco&test=ok


###
DELETE http://localhost:4000/delete/ok/ok2