###
GET  http://localhost:4000

###
POST http://localhost:4000/api/info
Content-Type: application/json

{
  "information" : "very cool"
}

###
PUT http://localhost:4000/api/
Content-Type: application/json

{
  "information" : "very cool"
}